openapi: 3.1.0
info:
  version: 1.0.0
  title: WalletFlow APP
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of WalletFlow App
tags:
  - name: Transactions
    description: Transactions operations.
  - name: Auth
    description: Auth operations.
  - name: Users
    description: Auth operations.
servers:
  - url: https://moneydashboard-back.onrender.com
paths:
  /api/auth/sign-up:
    post:
      $ref: ../swagger/paths/auth/sign-up.yaml
  /api/auth/sign-in:
    post:
      $ref: ../swagger/paths/auth/sign-in.yaml
  /api/auth/sign-out:
    post:
      $ref: ../swagger/paths/auth/sign-out.yaml
  /api/users/current:
    get:
      $ref: ../swagger/paths/users/current.yaml
  /api/transaction-categories:
    get:
      $ref: ../swagger/paths/categories/api-transaction-categories.yaml
  /api/transactions:
    get:
      $ref: ../swagger/paths/transactions/get-api-transactions.yaml
    post:
      $ref: ../swagger/paths/transactions/post-api-transactions.yaml
  /api/transactions/{transactionId}:
    patch:
      $ref: ../swagger/paths/transactions/{transactionId}/patch-api-transactions.yaml
    delete:
      $ref: ../swagger/paths/transactions/{transactionId}/delete-api-transactions.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
