openapi: 3.1.0
info:
  version: 1.0.0
  title: WalletFlow APP
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of WalletFlow App
tags:
  - name: WalletFlow
    description: WalletFlow operations.
  - name: Auth
    description: Auth operations.
servers:
  - url: https://moneydashboard-back.onrender.com

paths:
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/sing-up.yaml
  /auth/login:
    post:
      $ref: ../swagger/paths/auth/sing-in.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/users/current.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
